package com.example.graalvm.aot;

import com.example.graalvm.entity.Order;
import com.example.graalvm.entity.User;
import org.springframework.aot.hint.MemberCategory;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.aot.hint.TypeReference;

/**
 * Reflection Hints Registrar
 *
 * ================================================================
 * Why is this needed?
 * ================================================================
 *
 * GraalVM Native Image performs "closed world analysis" at build time.
 * It needs to know exactly which classes may be accessed reflectively
 * at runtime, because it can only include code that is reachable
 * from the entry point.
 *
 * Without this registration:
 *   - Class.forName("User") → Runtime error: ClassNotFoundException
 *   - objectMapper.readValue(json, User.class) → Fails (needs reflective deserializer)
 *   - Jackson serializers generated by reflection won't work
 *
 * Common reflective operations that need registration:
 * 1. JSON serialization/deserialization (Jackson, Gson)
 * 2. Bean property access (Spring, JPA, Hibernate)
 * 3. Annotation processing at runtime
 * 4. Dynamic class loading and method invocation
 *
 * ================================================================
 * MemberCategory options:
 * ================================================================
 * - PUBLIC_FIELDS:        public field access
 * - DECLARED_FIELDS:      all fields (including private)
 * - PUBLIC_METHODS:       public method invocation
 * - DECLARED_METHODS:     all methods
 * - PUBLIC_CONSTRUCTORS:  public constructor access
 * - DECLARED_CONSTRUCTORS: all constructors
 * - INTROSPECT_*:         reflection only (no invocation)
 * - INVOKE_*:             reflection + actual invocation
 */
public class ReflectionHints implements RuntimeHintsRegistrar {

    @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
        registerEntityHints(hints);
        registerDateTimeHints(hints);
        registerCollectionHints(hints);
    }

    /**
     * Register entity classes for full reflection.
     *
     * This covers:
     * - JSON serialization (Jackson needs getters/constructors)
     * - Bean property binding (Spring MVC form binding)
     * - Java serialization (implements Serializable)
     */
    private void registerEntityHints(RuntimeHints hints) {
        // User entity - full reflection for all operations
        hints.reflection().registerType(User.class, MemberCategory.values());

        // Order entity - full reflection
        hints.reflection().registerType(Order.class, MemberCategory.values());

        // Order enums - needed for switch statements and valueOf()
        hints.reflection().registerType(Order.OrderStatus.class,
                MemberCategory.DECLARED_FIELDS,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS);
        hints.reflection().registerType(Order.PaymentMethod.class,
                MemberCategory.DECLARED_FIELDS,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS);

        // Register BigDecimal (used in Order.amount fields)
        hints.reflection().registerType(java.math.BigDecimal.class,
                MemberCategory.DECLARED_FIELDS,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_DECLARED_METHODS);
    }

    /**
     * Register Java 8+ date/time types.
     *
     * LocalDateTime, LocalDate, LocalDateTime are commonly used in entities.
     * Without registration, these fail during JSON serialization in native image.
     */
    private void registerDateTimeHints(RuntimeHints hints) {
        hints.reflection().registerType(java.time.LocalDateTime.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS,
                MemberCategory.DECLARED_FIELDS);
        hints.reflection().registerType(java.time.LocalDate.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS);
        hints.reflection().registerType(java.time.LocalTime.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS);
        hints.reflection().registerType(java.time.Instant.class,
                MemberCategory.INVOKE_PUBLIC_METHODS);
        hints.reflection().registerType(java.time.Duration.class,
                MemberCategory.INVOKE_PUBLIC_METHODS);
    }

    /**
     * Register collection types.
     *
     * Generic collections with specific type parameters need registration
     * because GraalVM cannot infer element types at build time.
     */
    private void registerCollectionHints(RuntimeHints hints) {
        hints.reflection().registerType(java.util.ArrayList.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS);
        hints.reflection().registerType(java.util.HashMap.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS);
        hints.reflection().registerType(java.util.LinkedHashMap.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS);
        hints.reflection().registerType(java.util.LinkedList.class,
                MemberCategory.INVOKE_PUBLIC_CONSTRUCTORS,
                MemberCategory.INVOKE_PUBLIC_METHODS);
    }
}
