spring.application.name=astro-islands-basic
server.port=8080

# Thymelef\u914d\u7f6e\uff08\u5f00\u53d1\u73af\u5883\u5173\u95ed\u7f13\u5b58\uff09
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

logging.level.com.example=DEBUG
